### PR TITLE
fix: translate tooltip at view selection

### LINKED ISSUE #254: Missing translation for tooltip
A tooltip is missing a translation.
Screenshot 2023-12-04 at 13 15 45

### PR DESCRIPTION
**Pull request by LinaYahya**
closes #254

### CODE REVIEW

File: src/components/space/functionality/ViewSelect.tsx [hunk 1]
```diff
@@ -80,7 +80,7 @@ const ViewSelect = (): JSX.Element => {
         </FormControl>
       </Grid>
       <Grid item ml={2} mr={1}>
-        <Tooltip title={viewMessage}>
+        <Tooltip title={t(viewMessage)}>
```
Comment (pyphilia) [inline src/components/space/functionality/ViewSelect.tsx:83]: I would actually add the `t` higher, so it's clear what's the string you translate.

**Review by pyphilia — CHANGES_REQUESTED** [review]

**Review by spaenleh — APPROVED** [review]

**Review by pyphilia — APPROVED** [review]
