### PR TITLE
fix: prevent crash on waiting requests, update dependencies

### LINKED ISSUE #117: Uncaught TypeError: Cannot read properties of undefined (reading 'push')
A similar error exists in ItemsByUserChart

https://github.com/graasp/graasp-analytics/blob/319c2f656ac16e543a747f8ee73f8fb32f426c83/src/components/space/charts/ItemsByActionChart.js#L50

### PR DESCRIPTION
**Pull request by pyphilia**
This PR adds fallback results to prevent used on undefined values.
I've also updated the dependencies.

close #117

### CODE REVIEW

File: src/components/context/DataProvider.tsx [hunk 1]
```diff
@@ -0,0 +1,241 @@
...
+
+// fetch data only if enabled is true
+// enabled becomes true only if the user change the view in select
+
+type Props = {
+  children: JSX.Element | JSX.Element[];
+};
+
+const DataProvider = ({ children }: Props) => {
+  const [enabledArray, setEnabledArray] = useState({});
```
Comment (spaenleh) [inline src/components/context/DataProvider.tsx:57]: Should we initialize this to:
```ts
{
  [Context.BUILDER]: false,
  [Context.PLAYER]: false,
  [Context.LIBRARY]: false,
  [Context.UNKNOWN]: false,
}
```

File: src/components/context/DataProvider.tsx [hunk 2]
```diff
@@ -0,0 +1,241 @@
...
+    isError: builderIsError,
+    isLoading: builderIsLoading,
+  } = hooks.useActions(
+    {
+      itemId,
+      view: Context.BUILDER,
+      requestedSampleSize: DEFAULT_REQUEST_SAMPLE_SIZE,
+    },
+    { enabled: Boolean(enabledArray[Context.BUILDER]) },
+  ) as { data?: ActionDataRecord; isError: boolean; isLoading: boolean };
```
Comment (spaenleh) [inline src/components/context/DataProvider.tsx:82]: Why do you have to cast this ? Is it possible to type the hook instead ?

File: src/components/context/DataProvider.tsx [hunk 3]
```diff
@@ -0,0 +1,241 @@
...
+    { enabled: Boolean(enabledArray[Context.UNKNOWN]) },
+  ) as { data?: ActionDataRecord; isError: boolean; isLoading: boolean };
+
+  const {
+    data: itemData,
+    isError: itemIsError,
+    isLoading: itemIsLoading,
+  } = hooks.useItem(itemId);
+  const { data: itemChildren } = hooks.useChildren(itemId) as {
+    data: List<ItemRecord>;
```
Comment (spaenleh) [inline src/components/context/DataProvider.tsx:129]: Same about the casting here.

File: src/components/space/ChartsLayout.js [hunk 4]
```diff
@@ -13,18 +15,36 @@ import ChartsHeader from './charts-layout/ChartsHeader';
...
+          </Grid>
+          <Grid item xs={6}>
+            <Skeleton variant="rectangular" height={CONTAINER_HEIGHT} />
+          </Grid>
+          <Grid item xs={6}>
+            <Skeleton variant="rectangular" height={CONTAINER_HEIGHT} />
+          </Grid>
+          <Grid item xs={6}>
+            <Skeleton variant="rectangular" height={CONTAINER_HEIGHT} />
+          </Grid>
```
Comment (spaenleh) [inline src/components/space/ChartsLayout.js:43]: We could use a map to make this tidier If you want.

**Review by spaenleh — APPROVED** [review]
Looks good, just a few comments about improvements we can make to make the code look nicer  🐼
