### PR TITLE
fix: protect export actions for non-reads users

### LINKED ISSUE #365: Protect Export Actions route to only access for authorized members
Currently Export actions page is accessible over all members, While read access members are not allowed to export actions, So Protect the route for only authorized members

### PR DESCRIPTION
**Pull request by LinaYahya**
closes #365

### CODE REVIEW

File: src/components/layout/Sidebar.tsx [hunk 1]
```diff
@@ -31,46 +33,70 @@ const Sidebar: FC = () => {
...
-      />
+  const { data: memberships } = hooks.useItemMemberships(itemId);
+  const { data: currentMember } = hooks.useCurrentMember();
+
+  const userMemberships = memberships
+    ?.filter((m) => m.member.id === currentMember?.id)
+    .reduce((acc: PermissionLevel[], curr) => [...acc, curr.permission], []);
+
+  const memberPermissionOverItem =
+    userMemberships && PermissionLevelCompare.getHighest(userMemberships);
```
Comment (pyphilia) [inline src/components/layout/Sidebar.tsx:44]: We recently added `permission` within item, which corresponds to the highest permission the user has over the item. I think you can simply use that property ;)

File: src/components/layout/Sidebar.tsx [hunk 2]
```diff
@@ -31,46 +33,70 @@ const Sidebar: FC = () => {
...
-          to={buildAppsAnalyticsPath(itemId)}
-          disabled={disableMenuItem}
-        />
-      ) : (
-        <></>
-      )}
+  // read access users don't have permission over export actions
+  if (
+    memberPermissionOverItem &&
+    memberPermissionOverItem !== PermissionLevel.Read
```
Comment (pyphilia) [inline src/components/layout/Sidebar.tsx:86]: You can use `PermissionLevelCompare.gte(myPermission, Permission.Write)`

File: src/components/pages/Item/ExportAnalyticsPage.tsx [hunk 3]
```diff
@@ -26,6 +31,16 @@ const CustomListItem = styled(ListItem)(({ theme }) => ({
...
+  const { itemId } = useParams();
+  const { data: memberships } = hooks.useItemMemberships(itemId);
+  const { data: currentMember } = hooks.useCurrentMember();
+
+  const userMemberships = memberships
+    ?.filter((m) => m.member.id === currentMember?.id)
+    .reduce((acc: PermissionLevel[], curr) => [...acc, curr.permission], []);
+
+  const memberPermissionOverItem =
+    userMemberships && PermissionLevelCompare.getHighest(userMemberships);
```
Comment (pyphilia) [inline src/components/pages/Item/ExportAnalyticsPage.tsx:43]: Same as above.

File: src/components/pages/Item/ExportAnalyticsPage.tsx [hunk 4]
```diff
@@ -59,35 +74,44 @@ const ExportAnalyticsPage = (): JSX.Element => {
...
-          <ExportData />
-        </Box>
-      </Stack>
-    </Container>
-  );
+
+  if (
+    memberPermissionOverItem &&
+    memberPermissionOverItem !== PermissionLevel.Read
+  ) {
```
Comment (pyphilia) [inline src/components/pages/Item/ExportAnalyticsPage.tsx:81]: Same as above.

File: src/components/pages/Item/ExportAnalyticsPage.tsx (hunk 3 above)
Comment (pyphilia) [reply src/components/pages/Item/ExportAnalyticsPage.tsx:43]: Also I think your implementation does not handle loading, what if the takes time to get the memberships/item? It will redirect directly no?

**Review by pyphilia — CHANGES_REQUESTED** [review]
Thanks for the PR! We've added an handy permission property I think you can use it ;)

**Review by pyphilia — APPROVED** [review]
